### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by devn** [getsentry/sentry-clj#14]
https://github.com/getsentry/sentry-clj/blob/5f671a7082a957bc25efe47c2889d31229d95de6/src/sentry_clj/internal.clj#L13-L28

Is there a reason why this code exists? What happens without `internal.clj`?

**Comment by bretthoerner** [comment]
This allows for providing the proper (Java) interfaces the Java SDK requires to add another (Sentry) interface, but by providing Clojure data.

So `(internal/->CljInterface "user" {:foo 1})` becomes `{"user": {"foo": 1}}` in the event document, instead of having to use the verbose Java APIs to construct the `UserInterface`.
